[book]
title = "pcapliteracy"
authors = ["laufeynumber1fan"]
description = "Fan project about pcaps."
language = "en"
src = "src"

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
default-theme = "light"
preferred-dark-theme = "light"
smart-punctuation = true
input-404 = "404.md"
git-repository-url = "https://github.com/Laufeynumber1fan/pcapliteracy"
git-repository-icon = "fa-github"

# remove print symbol on the top right corner
[output.html.print]
enable = false

# disable search button
[output.html.search]
enable = false
expand = false

[output.html.playground]
editable = true

[output.html.code.hidelines]
rust = "~"

# mdbook-alerts
[preprocessor.alerts]